name: ceinfo
description: Lets players know ce list by using the /ceinfo command.
author: kenygamer
main: kenygamer\ServerRules\Main
load: POSTWORLD
version: 1.0.0
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
commands:
    ceinfo:
        description: Displays ce list
permissions:
    ceinfo.info:
        default: true
        description: Allow players to use the /ceinfo command
