---
rule-0: "§l§c»§r§eCustom Enchantment List§l§c«§r"
rule-1: "§aGlobal Enchants"
rule-2: "§bLifesteal: §fGives you half a heart back whenever you punch an enemy."
rule-3: "§bBlind: §fBlinds the enemy."
rule-4: "§bDeathbringer: §fDoubles your damage."
rule-5: "§bGooey: §fHitting your enemy rapidly causes the enemy to be flinged into the air."
rule-6: "§bPoison: §fPoisons the enemy."
rule-7: "§bAutorepair: §fAutomatically repairs your armour/weapon when hit."
rule-8: "§bCripplingsrike: §fCripples your enemy on hit."
rule-9: "§bVampire: §fHeals you by half of your damage."
rule-10: "§bAerial: §fAttacking while sprinting increases your damage."
rule-11: "§bWither: §fWithers your enemy on hit."
rule-12: "§bDisarming: §fDisarms your enemy."
rule-13: "§aTools"
rule-14: "§bExplosive: §fToo OP. Donate to get this."
rule-15: "§bSmelting: §fSmelts blocks when mining"
rule-16: "§bEnergizing: §fGives you haste for faster mining."
rule-17: "§bQuickening: §fBreaking blocks give you speed effect."
rule-18: "§aBow"
rule-19: "§bMolotov: §fAttaches a molotov to the arrow, tends to start fires."
rule-20: "§bVolley: §fFires multiple arrows in a cone in front of you."
rule-21: "§bPiercing: §fIgnores enemy's armour"
rule-22: "§bShuffle: §fSwitches your position with your enemy's position."
rule-23: "§bHealing: §fHeals your target for 1 heart per level."
rule-24: "§bBlaze: §fShoots fireballs instead of arrows"
rule-25: "§aArmour"
rule-26: "§bMolten: §fSets the enemy that hit you on fire."
rule-27: "§bEnlighted: §fHeals you when hit."
rule-28: "§bHardened: §fApplies Weakness to the enemy that hit you."
rule-29: "§bPoisoned: §fPoisons the enemy that hit you."
rule-30: "§bFrozen: §fSlows the enemy that hit you."
rule-31: "§bObsidianshield: §fGives you Fireresistance."
rule-32: "§bRevulsion: §fApplies Nausea to the enemy that hit you."
rule-33: "§bSelf Destruct: §fSpawn live TNT on death."
rule-34: "§bCursed: §fApplies the Wither effect to your enemy."
rule-35: "§bEndershift: §fGives you speed boost and hp when low."
rule-36: "§bDrunk: §fGives slowness, mining fatigue and confusion to attackers."
rule-37: "§bBerserker: §fWhen low on health, you gain extreme strength."
rule-38: "§bCloaking: §fWhen hit, you gain stealth for a few seconds."
rule-39: "§aHelmet"
rule-40: "§bGlowing: §fGives you nightvision."
rule-41: "§aBoots"
rule-42: "§bGears: §fGives you a Speedboost."
rule-43: "§bSprings: §fGives you a Jumpboost."
rule-44: "§bStomp: §fLet the enemy take your fall damage."
...
